include: 'https://gitlab.com/nomadic-labs/gitlab-ocaml-ci-example/-/raw/main/.gitlab-ci.yml'

.build-matrix:
  parallel:
    matrix:
    - OCAML_COMPILER: "4.13.1"

variables:
  CLEAN_OPAM_CACHE: "false"
  CLEAN_DUNE_CACHE: "false"
  DUNE_BUILD_TARGETS: "@install"
  DUNE_TEST_TARGETS: "@runtest"
  DUNE_DOC_TARGETS: "" # no doc for now because of unmet dependency
